2021-01-20 18:36:37.464 WARNING _internal - _log:  * Debugger is active!
2021-01-20 18:36:37.465 INFO _internal - _log:  * Debugger PIN: 103-468-654
2021-01-20 18:36:45.453 INFO _internal - _log: 127.0.0.1 - - [20/Jan/2021 18:36:45] "[33mGET /ad HTTP/1.1[0m" 404 -
2021-01-20 18:36:47.742 INFO datacontrol - get_covid_data: Getting Covid data from https://www.worldometers.info/coronavirus/country/lebanon/
2021-01-20 18:36:47.742 INFO datacontrol - get_covid_data: Trying to get Url response
2021-01-20 18:36:47.744 DEBUG connectionpool - _new_conn: Starting new HTTPS connection (1): www.worldometers.info:443
2021-01-20 18:36:48.161 DEBUG connectionpool - _make_request: https://www.worldometers.info:443 "GET /coronavirus/country/lebanon/ HTTP/1.1" 200 None
2021-01-20 18:36:48.286 INFO datacontrol - get_covid_data: Getting number of cases, deaths and recoveries
2021-01-20 18:36:48.297 DEBUG datacontrol - get_covid_data: <daily.Daily object at 0x7f78332cedc0>
2021-01-20 18:36:48.298 INFO datacontrol - get_covid_data: Cases: 264,647    Deaths: 2,084    Recoveries: 157,202
2021-01-20 18:36:48.298 INFO routes - dataAdd: Pushing <id 2021-01-20> to database
2021-01-20 18:36:48.323 ERROR routes - dataAdd: Key already exists
2021-01-20 18:36:48.323 ERROR routes - dataAdd: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "daily_pkey"
DETAIL:  Key (date)=(2021-01-20) already exists.

[SQL: INSERT INTO daily (date, total_cases, total_deaths, total_recoveries) VALUES (%(date)s, %(total_cases)s, %(total_deaths)s, %(total_recoveries)s)]
[parameters: {'date': '2021-01-20', 'total_cases': None, 'total_deaths': None, 'total_recoveries': None}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-20 18:36:48.324 INFO _internal - _log: 127.0.0.1 - - [20/Jan/2021 18:36:48] "[37mGET /add HTTP/1.1[0m" 200 -
